eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  rule-service:
    endpoints:
      endpoint:
        uri: http://RULE-SERVICE/otar/rule
  merchant-service:
    endpoints:
      endpoint:
        uri: http://MERCHANT-SERVICE/otar/merchant
  airtime-service:
    endpoints:
      endpoint:
        uri: http://AIRTIME-SERVICE/otar/airtime
  airtime-adaptor-service:
    endpoints:
      endpoint:
        uri: http://AIRTIME-ADAPTOR-SERVICE/otar/airtimeadaptor
  erp-adaptor-service:
    endpoints:
      endpoint:
        uri: http://ERP-ADAPTOR-SERVICE/otar/erpadaptor



